name: Status Embeds

on:
  workflow_run:
    workflows:
      - Test & deploy
      - Linting & testing
    types:
      - completed

jobs:
  embed:
    name: Send Status Embed
    runs-on: ubuntu-latest
    steps:
      - name: Github Actions Embed
        uses: SebastiaanZ/github-status-embed-for-discord@v0.2.1
        with:
          webhook_id: '${{ secrets.webhook_id }}'
          webhook_token: ${{ secrets.webhook_token }}

          workflow_name: ${{ github.event.workflow_run.name }}
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          status: ${{ github.event.workflow_run.conclusion }}
          actor: ${{ github.actor }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          sha: ${{ github.event.workflow_run.head_sha }}
